[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[project]
name = "behaviour-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nicegui>=3.15.0",
    "pandas>=3.0.5",
    "typer>=0.27.0",
    "polars",
    "ipywidgets>=8.1.8",
]
[project.scripts]
behaviour-hub = "timeline.cli:app"

[tool.hatch.build.targets.wheel]
      packages = ["timeline"]

[dependency-groups]
dev = [
    "jupyterlab",
    "ipykernel",
    "matplotlib",

]
